# Generated by Django 5.0.7 on 2024-10-01 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colddm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ColdDMSave',
        ),
    ]
