# Generated by Django 5.0.7 on 2024-10-13 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colddm', '0007_usercolddmstats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercolddmstats',
            options={'verbose_name': 'User Cold DM Stats', 'verbose_name_plural': 'User Cold DM Stats'},
        ),
    ]
