# Generated by Django 5.0.7 on 2024-10-13 10:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colddm', '0008_alter_usercolddmstats_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='colddm',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='colddm',
            name='saved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cold_dms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DailyColdDMStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('cold_dms_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_cold_dm_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserColdDMStats',
        ),
    ]
