# Generated by Django 5.0.7 on 2024-10-13 11:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colddm', '0010_remove_colddm_created_at_alter_colddm_saved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colddm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
