# Generated by Django 5.0.7 on 2024-10-15 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colddm', '0012_alter_colddm_saved_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercolddmstats',
            options={'verbose_name': 'User Cold DM Stats'},
        ),
    ]
