# Generated by Django 5.0.7 on 2024-10-15 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colddm', '0013_alter_usercolddmstats_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercolddmstats',
            options={'verbose_name_plural': 'User Cold DM Stats'},
        ),
    ]
