# Generated by Django 5.0.7 on 2024-10-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='banners/')),
                ('profile_picture', models.ImageField(upload_to='profiles/')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('instagram_link', models.URLField()),
                ('tiktok_link', models.URLField()),
                ('custom_link', models.CharField(max_length=200)),
            ],
        ),
    ]
