# Generated by Django 5.0.7 on 2024-10-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autosell',
            name='custom_link',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
