# Generated by Django 5.0.7 on 2024-10-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosell', '0003_autosell_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='autosell',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
