# Generated by Django 5.0.7 on 2024-10-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosell', '0006_remove_autosell_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autosell',
            name='banner',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='autosell',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
