# Generated by Django 5.0.7 on 2024-10-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosell', '0007_alter_autosell_banner_alter_autosell_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autosell',
            name='banner',
            field=models.ImageField(upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='autosell',
            name='profile_picture',
            field=models.ImageField(upload_to='profiles/'),
        ),
    ]
