# Generated by Django 5.0.7 on 2024-10-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosell', '0009_alter_autosell_name_alter_autosell_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autosell',
            name='banner',
            field=models.ImageField(max_length=500, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='autosell',
            name='profile_picture',
            field=models.ImageField(max_length=500, upload_to='profiles/'),
        ),
    ]
