# Generated by Django 5.0.12 on 2025-03-15 12:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosell', '0010_alter_autosell_banner_alter_autosell_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autosellview',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='autosell',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='autosell',
            name='tiktok_link',
        ),
        migrations.RemoveField(
            model_name='autosellview',
            name='autosell',
        ),
        migrations.RemoveField(
            model_name='autosellview',
            name='view_date',
        ),
        migrations.AddField(
            model_name='autosellview',
            name='auto_sell',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='views', to='autosell.autosell'),
        ),
        migrations.AddField(
            model_name='autosellview',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autosellview',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='autosell',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('pinterest', 'Pinterest'), ('discord', 'Discord Server'), ('snapchat', 'Snapchat'), ('custom', 'Custom Link')], max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('auto_sell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='autosell.autosell')),
            ],
        ),
    ]
