# Generated by Django 5.0.12 on 2025-03-15 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosell', '0012_autosell_show_social_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autosellview',
            name='auto_sell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='views', to='autosell.autosell'),
        ),
    ]
