# Generated by Django 5.0.12 on 2025-03-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosell', '0015_landingpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
