# Generated by Django 5.0.12 on 2025-03-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosell', '0016_alter_landingpage_name'),
        ('products', '0046_alter_unlimitedproduct_landing_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='one_time_products',
            field=models.ManyToManyField(blank=True, related_name='landing_page_onetime', to='products.onetimeproduct'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='unlimited_products',
            field=models.ManyToManyField(blank=True, related_name='landing_page_unlimited', to='products.unlimitedproduct'),
        ),
    ]
