# Generated by Django 5.0.12 on 2025-03-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosell', '0017_landingpage_one_time_products_and_more'),
        ('products', '0061_alter_onetimeproductcategory_landing_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='one_time_products',
            field=models.ManyToManyField(blank=True, related_name='product_landing_pages', to='products.onetimeproduct'),
        ),
    ]
