# Generated by Django 5.0.7 on 2024-08-09 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unlimitedproduct',
            name='user',
        ),
        migrations.DeleteModel(
            name='OneTimeProduct',
        ),
        migrations.DeleteModel(
            name='UnlimitedProduct',
        ),
    ]
