# Generated by Django 5.0.7 on 2024-08-10 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_onetimeproduct_products_productitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitem',
            old_name='content',
            new_name='product_content',
        ),
    ]
