# Generated by Django 5.0.7 on 2024-08-10 09:44

import django.db.models.deletion
import products.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_content_productitem_product_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimeproduct',
            name='user',
        ),
        migrations.CreateModel(
            name='OneTimeProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='onetimeproduct',
            name='category',
            field=models.ForeignKey(default=products.models.get_default_category, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.onetimeproductcategory'),
        ),
    ]
