# Generated by Django 5.0.7 on 2024-08-10 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_onetimeproduct_user_onetimeproductcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimeproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.onetimeproductcategory'),
        ),
    ]
