# Generated by Django 5.0.7 on 2024-08-10 10:04

import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_onetimeproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimeproduct',
            name='category',
            field=models.ForeignKey(default=products.models.get_default_category, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.onetimeproductcategory'),
        ),
    ]
