# Generated by Django 5.0.7 on 2024-08-10 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_onetimeproduct_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimeproduct',
            name='product_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onetimeproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.onetimeproductcategory'),
        ),
    ]
