# Generated by Django 5.0.7 on 2024-10-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_onetimeproductcategory_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unlimitedproduct',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
