# Generated by Django 5.0.7 on 2024-10-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_unlimitedproduct_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimeproduct',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='onetimeproduct',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
