# Generated by Django 5.0.7 on 2024-10-06 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_productsale_unlimited_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsale',
            name='unlimited_product',
        ),
        migrations.AlterField(
            model_name='onetimeproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.unlimitedproduct'),
        ),
    ]
