# Generated by Django 5.0.7 on 2024-10-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_onetimeproductcategory_show_on_custom_lander'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimeproduct',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductItem',
        ),
    ]
