# Generated by Django 5.0.7 on 2024-10-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_onetimeproduct_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimeproduct',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
