# Generated by Django 5.0.7 on 2024-10-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_unlimitedproduct_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimeproduct',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR')], max_length=3),
        ),
    ]
