# Generated by Django 5.0.7 on 2024-10-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_onetimeproduct_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='unlimitedproduct',
            name='btc_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unlimitedproduct',
            name='eth_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unlimitedproduct',
            name='ltc_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unlimitedproduct',
            name='usdt_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
