# Generated by Django 5.0.7 on 2024-10-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_onetimeproduct_btc_price_onetimeproduct_eth_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimeproduct',
            name='btc_price',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='onetimeproduct',
            name='eth_price',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='onetimeproduct',
            name='ltc_price',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='onetimeproduct',
            name='usdt_price',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='unlimitedproduct',
            name='btc_price',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='unlimitedproduct',
            name='eth_price',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='unlimitedproduct',
            name='ltc_price',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='unlimitedproduct',
            name='usdt_price',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True),
        ),
    ]
