# Generated by Django 5.0.7 on 2024-10-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_onetimeproduct_btc_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimeproduct',
            name='test_price',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='unlimitedproduct',
            name='test_price',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True),
        ),
    ]
