# Generated by Django 5.0.7 on 2024-10-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_onetimeproduct_test_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimeproduct',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR')], max_length=4),
        ),
        migrations.AlterField(
            model_name='unlimitedproduct',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR')], max_length=4),
        ),
    ]
