# Generated by Django 5.0.7 on 2024-10-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_alter_onetimeproduct_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsale',
            name='currency',
            field=models.CharField(max_length=4),
        ),
    ]
