# Generated by Django 5.0.7 on 2024-10-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_alter_productsale_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimeproduct',
            name='sol_price',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='unlimitedproduct',
            name='sol_price',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True),
        ),
    ]
