# Generated by Django 5.0.7 on 2024-10-26 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_userincome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc', models.CharField(blank=True, max_length=255, null=True)),
                ('ltc', models.CharField(blank=True, max_length=255, null=True)),
                ('sol', models.CharField(blank=True, max_length=255, null=True)),
                ('eth', models.CharField(blank=True, max_length=255, null=True)),
                ('usdt_bep20', models.CharField(blank=True, max_length=255, null=True)),
                ('usdt_erc20', models.CharField(blank=True, max_length=255, null=True)),
                ('usdt_prc20', models.CharField(blank=True, max_length=255, null=True)),
                ('usdt_sol', models.CharField(blank=True, max_length=255, null=True)),
                ('usdt_trc20', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='products_userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserIncome',
        ),
    ]
