# Generated by Django 5.0.7 on 2024-10-26 20:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_userincome_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userincome',
            name='ltct_total',
            field=models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=30),
        ),
    ]
