# Generated by Django 5.0.7 on 2024-10-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_userincome_ltct_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimeproductcategory',
            name='category_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='unlimitedproduct',
            name='product_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
