# Generated by Django 5.0.7 on 2024-11-05 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_onetimeproductcategory_category_image_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onetimeproductcategory',
            options={'verbose_name_plural': 'One time product categories'},
        ),
    ]
