# Generated by Django 5.0.7 on 2024-11-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_alter_onetimeproductcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unlimitedproduct',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
