# Generated by Django 5.0.12 on 2025-03-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_onetimeproduct_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimeproductcategory',
            name='show_on_custom_lander',
        ),
        migrations.RemoveField(
            model_name='unlimitedproduct',
            name='show_on_custom_lander',
        ),
    ]
