# Generated by Django 5.0.12 on 2025-03-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosell', '0015_landingpage'),
        ('products', '0043_remove_onetimeproductcategory_show_on_custom_lander_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimeproduct',
            name='landing_pages',
            field=models.ManyToManyField(blank=True, related_name='one_time_products', to='autosell.landingpage'),
        ),
        migrations.AlterField(
            model_name='unlimitedproduct',
            name='landing_pages',
            field=models.ManyToManyField(blank=True, related_name='unlimited_products', to='autosell.landingpage'),
        ),
        migrations.DeleteModel(
            name='LandingPage',
        ),
    ]
