# Generated by Django 5.0.12 on 2025-03-15 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosell', '0016_alter_landingpage_name'),
        ('products', '0044_alter_onetimeproduct_landing_pages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unlimitedproduct',
            name='landing_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autosell.landingpage'),
        ),
    ]
