# Generated by Django 5.0.12 on 2025-03-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosell', '0017_landingpage_one_time_products_and_more'),
        ('products', '0046_alter_unlimitedproduct_landing_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimeproduct',
            name='landing_pages',
            field=models.ManyToManyField(blank=True, related_name='product_onetime', to='autosell.landingpage'),
        ),
    ]
