# Generated by Django 5.0.12 on 2025-03-16 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_alter_onetimeproduct_landing_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unlimitedproduct',
            name='landing_page',
        ),
    ]
