# Generated by Django 5.0.12 on 2025-03-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosell', '0017_landingpage_one_time_products_and_more'),
        ('products', '0048_remove_unlimitedproduct_landing_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimeproductcategory',
            name='landing_pages',
            field=models.ManyToManyField(blank=True, related_name='categories', to='autosell.landingpage'),
        ),
    ]
