# Generated by Django 5.0.12 on 2025-03-16 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0051_alter_unlimitedproduct_landing_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimeproductcategory',
            name='landing_pages',
        ),
    ]
