# Generated by Django 5.0.12 on 2025-03-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosell', '0017_landingpage_one_time_products_and_more'),
        ('products', '0055_remove_onetimeproductcategory_landing_pages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unlimitedproduct',
            name='landing_pages',
            field=models.ManyToManyField(blank=True, related_name='landing_page_unlimited', to='autosell.landingpage'),
        ),
    ]
