# Generated by Django 5.0.12 on 2025-03-16 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0056_alter_unlimitedproduct_landing_pages'),
    ]

    operations = [
    ]
