# Generated by Django 5.0.12 on 2025-03-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosell', '0017_landingpage_one_time_products_and_more'),
        ('products', '0060_onetimeproductcategory_landing_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimeproductcategory',
            name='landing_pages',
            field=models.ManyToManyField(blank=True, related_name='one_time_categories', to='autosell.autosell'),
        ),
    ]
