# Generated by Django 5.0.12 on 2025-03-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosell', '0018_alter_landingpage_one_time_products'),
        ('products', '0061_alter_onetimeproductcategory_landing_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimeproduct',
            name='landing_pages',
            field=models.ManyToManyField(blank=True, related_name='landing_page_one_time_products', to='autosell.landingpage'),
        ),
    ]
