# Generated by Django 5.0.12 on 2025-03-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosell', '0019_alter_landingpage_one_time_products'),
        ('products', '0065_alter_onetimeproduct_landing_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimeproduct',
            name='landing_pages',
            field=models.ManyToManyField(blank=True, related_name='onetime_products', to='autosell.autosell'),
        ),
    ]
