# Generated by Django 5.0.12 on 2025-03-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0066_alter_onetimeproduct_landing_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsale',
            name='conversion_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productsale',
            name='fee_details_fetched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productsale',
            name='payout_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productsale',
            name='platform_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productsale',
            name='stripe_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productsale',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
