# Generated by Django 5.0.12 on 2025-03-18 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0067_productsale_conversion_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsale',
            name='stripe_payout',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='customer_email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.onetimeproduct'),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='unlimited_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.unlimitedproduct'),
        ),
    ]
