# Generated by Django 5.0.12 on 2025-03-18 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0069_alter_userincome_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsale',
            name='conversion_fee',
        ),
        migrations.RemoveField(
            model_name='productsale',
            name='stripe_payout',
        ),
        migrations.RemoveField(
            model_name='productsale',
            name='tax_amount',
        ),
    ]
