# Generated by Django 5.0.12 on 2025-03-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0071_remove_userincome_btc_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsale',
            name='payout_processed',
            field=models.BooleanField(default=False),
        ),
    ]
