# Generated by Django 5.0.12 on 2025-03-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0072_productsale_payout_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsale',
            name='converted_amount_eur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
