# Generated by Django 5.0.12 on 2025-03-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0073_productsale_converted_amount_eur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsale',
            name='payout_processed',
        ),
        migrations.AddField(
            model_name='productsale',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
