# Generated by Django 5.0.12 on 2025-02-17 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0022_usersubscription_cancel_at_period_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='features',
        ),
        migrations.AlterField(
            model_name='subscriptionprice',
            name='interval',
            field=models.CharField(choices=[('month', 'Monthly'), ('week', 'Weekly'), ('year', 'Annual')], default='month', max_length=120),
        ),
        migrations.CreateModel(
            name='SubscriptionFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short title or name of the feature.', max_length=255)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='subscription_features/')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_set', to='subscriptions.subscription')),
            ],
        ),
    ]
