# Generated by Django 5.0.12 on 2025-02-17 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0023_remove_subscription_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_subscriptions', to='subscriptions.subscriptionprice'),
        ),
    ]
