# Generated by Django 5.0.12 on 2025-02-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0025_remove_usersubscription_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionfeature',
            name='icon',
            field=models.URLField(blank=True, help_text='URL of the feature icon.', max_length=500, null=True),
        ),
    ]
