# Generated by Django 5.0.12 on 2025-02-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0026_alter_subscriptionfeature_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionfeature',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='temp/'),
        ),
    ]
