# Generated by Django 5.0.12 on 2025-02-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0028_alter_subscriptionfeature_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionfeature',
            name='icon',
            field=models.URLField(blank=True, help_text='Supabase image URL', max_length=500, null=True),
        ),
    ]
