# Generated by Django 5.0.12 on 2025-02-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0035_alter_subscriptionprice_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='order',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='permissions',
            field=models.ManyToManyField(blank=True, limit_choices_to={'codename__in': ['pro', 'starter'], 'content_type__app_label': 'subscriptions'}, to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='subscriptionfeature',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subscriptionprice',
            name='featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscriptionprice',
            name='order',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('trailing', 'Trailing'), ('incomplete', 'Incomplete'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
    ]
