# Generated by Django 5.0.12 on 2025-02-19 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0038_currentsubscriptionpurchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentSubscriptionPurchase',
        ),
    ]
