# Generated by Django 5.0.7 on 2024-10-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_userprofile_btc_wallet_userprofile_eth_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='revolut_tag',
            field=models.CharField(blank=True, null=True),
        ),
    ]
