# Generated by Django 5.0.12 on 2025-03-18 21:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_payoutrequest_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payoutrequest',
            old_name='contact_info',
            new_name='payout_address',
        ),
        migrations.RenameField(
            model_name='payoutrequest',
            old_name='payment_method',
            new_name='payout_method',
        ),
        migrations.RemoveField(
            model_name='payoutrequest',
            name='contact_method',
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='conversion_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='eur_equivalent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('BTC', 'BTC'), ('LTC', 'LTC'), ('SOL', 'SOL'), ('ETH', 'ETH'), ('USDT.BEP20', 'USDT (BEP20)'), ('USDT.ERC20', 'USDT (ERC20)'), ('USDT.PRC20', 'USDT (PRC20)'), ('USDT.TRC20', 'USDT (TRC20)'), ('USDT.SOL', 'USDT (SOL)')], max_length=10),
        ),
    ]
