# Generated by Django 5.0.7 on 2024-09-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255)),
                ('channel_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='autoaddetail',
            name='config',
        ),
        migrations.RemoveField(
            model_name='autoaduser',
            name='user',
        ),
        migrations.DeleteModel(
            name='AutoAdConfig',
        ),
        migrations.DeleteModel(
            name='AutoAdDetail',
        ),
        migrations.DeleteModel(
            name='AutoAdUser',
        ),
    ]
