# Generated by Django 5.0.7 on 2024-09-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoad', '0002_channels_remove_autoaddetail_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channels',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='channels',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='channels',
            name='seconds',
            field=models.IntegerField(default=0),
        ),
    ]
