# Generated by Django 5.0.7 on 2024-10-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoad', '0004_channels_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='channel_id',
            field=models.CharField(max_length=255),
        ),
    ]
