# Generated by Django 5.0.7 on 2024-10-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoad', '0005_alter_channels_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='channel_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
