# Generated by Django 5.0.7 on 2024-10-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoad', '0010_delete_dailyadcount_channels_ad_count_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='channels',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
