# Generated by Django 5.0.7 on 2024-10-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoad', '0011_channels_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='channels',
            name='remaining_time',
            field=models.IntegerField(default=0),
        ),
    ]
