# Generated by Django 5.0.7 on 2024-10-13 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoad', '0013_remove_channels_remaining_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channels',
            name='confirmed',
        ),
    ]
