# Generated by Django 5.0.7 on 2024-10-15 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoad', '0014_remove_channels_confirmed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channels',
            options={'verbose_name_plural': 'Channels'},
        ),
    ]
