name : 1 - Hello world github actions


on: 
  workflow_dispatch: 
  push: # git push
    branch:
      - main

jobs: 
  hello: 
    runs-on: ubuntu-latest
    steps:
      - name: Helo there
        run: echo "hello"