name : 1 - Hello world github actions


on: 
  workflow_dispatch: 
  # schedule:
  #   - cron: '30 15 * * *'
  # push: # git push
  #   branch:
  #     - main

jobs: 
  hello: 
    runs-on: ubuntu-latest
    steps:
      - name: Helo there
        run: echo "hello"