name: 3 - Test Django Env Vars

on: 
  workflow_dispatch: 
  push:
    branches:
      - main

jobs: 
  test: 
    steps:
      - name: Setup Python
          python-version: '3.12'
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Django Tests
        working-directory: ./src
        env:
          DJANGO_SECRET_KEY: not-good
        run: |
          python manage.py test
